/**
 * UI String Resources
 * Centralized dictionary for all application text.
 */
export const UI_TEXT = {
  appName: "Eternia Food Desk",
  headerTitle: "ETERNIA FOOD DESK 2026",
  tagline: "Track every plate, flat by flat.",
  loading: "Loading data...",
  offlineMode: "Offline mode",
  day: "Day",
  meal: "Meal",
  split: "Split",
  pending: "Pending",
  flat: "Flat",
  payment: "Payment",
  downloadReport: "Download Report",
  reportFilters: "Report Filters",
  selectDay: "Select Day:",
  selectMeal: "Select Meal:",
  operationalSummary: "Operational Summary",
  noMealsSelected: "All members have taken this meal or no meals selected.",
  platesDemand: "Plates Demand",
  plates: "Plates",
  totalDemand: "Total Demand",
  demandSplit: "Demand Split",
  mealTaken: "Meal Taken",
  mealNotTaken: "Meal Not Taken",
  parcelsNeeded: "Parcels Needed",
  totalParcels: "Total Parcels",
  resSuffix: "Res",
  guestSuffix: "Guest",
  taken: "Taken",
  missed: "Missed",
  demand: "Demand",
  parcels: "Parcels",
  total: "Total",
  totalCollection: "Total Collection",
  totalDemandLabel: "Total Demand",
  platesDemand: "Plates Demand",
  plates: "Plates",
  paymentIntegration: "Payment Integration",
  paymentIntegrationHelper: "Enable tracking for subscriptions",
  subscriptions: "Subscriptions",
  personNotTaken: "person Not Taken",
  personsNotTaken: "persons Not Taken",
  mealDisabled: "This meal is disabled for the selected day.",
  block: "BLOCK",
  flatUpper: "Flat",
  people: "People",
  parcelAbbr: "P",
  guestTaken: "Guest Taken",
  paymentDetails: "Payment Details",
  upi: "UPI",
  cash: "Cash",
  bankTransfer: "Bank transfer",
  egPeople: "e.g. 2",
  pass: "Pass",

  // Home Screen
  activePasses: "ACTIVE PASSES",
  totalPeopleLabel: "TOTAL MEMBERS",
  viewMenu: "View Menu",
  dashboard: "Dashboard",
  guestButton: "Guest",
  guestManagement: "Guest Management",
  report: "Report",
  scanQr: "Scan QR",
  addFlat: "Add Pass",
  searchPlaceholder: "Search block or flat no.",
  noRecords: "No flat records found.",
  noMatches: "No matching flats.",
  flexibleMeals: "Flexible meals",
  personSuffix: " person",
  personsSuffix: " persons",
  rs: "Rs",

  // Details Screen
  flatIdPrefix: "FLAT ",
  passIdentity: "PASS IDENTITY",
  passDetails: "Pass Details",
  subscriptionSummary: "Subscription Summary",
  detailsSubtitle: "Pass Details",
  registeredPersonSuffix: " registered person",
  registeredPersonsSuffix: " registered persons",
  deleteRecord: "Delete Record",
  registeredPersonSuffix: " registered person",
  registeredPersonsSuffix: " registered persons",
  foodPlan: "Food plan",
  foodChoiceByPerson: "Food choice by member",
  foodChoiceHelper: "B=Breakfast, L=Lunch, D=Dinner. Dot indicates Parcel. P=Person/Member.",
  foodTakenByPerson: "Food taken by member",
  foodTakenHelper:
    "Saved food collection status (B=Breakfast, L=Lunch, D=Dinner). P=Person/Member.",
  editPass: "Edit",
  showQr: "Show QR",

  // Menu Screen
  foodMenu: "Food Menu",
  menuSubtitle: "Daily delicious menu for the puja days.",
  menuEditorSubtitle: "Manage daily breakfast, lunch, and dinner.",
  updateMenuItems: "Update",
  saveMenu: "Save Menu",
  saving: "Saving...",
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
  addVegItem: "Add veg item...",
  addNonVegItem: "Add non-veg item...",
  veg: "Veg",
  nonVeg: "Non-Veg",
  success: "Success",
  menuUpdated: "Menu updated successfully",
  error: "Error",
  couldNotUpdateMenu: "Could not update menu",
  breakfastLabel: "B",
  lunchLabel: "L",
  dinnerLabel: "D",

  // Dashboard Screen
  dashboardTitle: "Food Dashboard",
  dashboardSubtitle: "Daily Kitchen Counts.",
  dailyMealDemand: "Daily Meal Demand",
  dailyDemandSummary: "Demand Summary",
  guestTotal: "Guest Total",

  // Dashboard Metrics
  bVeg: "Veg",
  bNonVeg: "Non-Veg",
  bParcel: "Parcel",
  bP_Taken: "Parcel Taken",
  bTaken: "Total Taken",
  lVeg: "Veg",
  lNonVeg: "Non-Veg",
  lParcel: "Parcel",
  lP_Taken: "Parcel Taken",
  lTaken: "Total Taken",
  dVeg: "Veg",
  dNonVeg: "Non-Veg",
  dParcel: "Parcel",
  dP_Taken: "Parcel Taken",
  dTaken: "Total Taken",
  guestVeg: "Guest Veg",
  guestNonVeg: "Guest Non-Veg",
  guestTaken: "Guest Taken",
  guestVegTaken: "Guest Veg Taken",
  guestNonVegTaken: "Guest Non-Veg Taken",
  vegTaken: "Veg Taken",
  nonVegTaken: "Non-Veg Taken",

  // Scanner Screen
  qrScanner: "QR SCANNER",
  cameraAccess: "Camera Access",
  cameraAccessSubtitle: "Allow camera access to validate a flat pass.",
  allowCamera: "Allow Camera",
  scanFrameHint: "Place a flat QR inside the frame",
  scanError: "This QR does not match a registered pass.",

  // QR Pass Screen
  foodPass: "Food Pass",
  qrIdentityStay: "This code stays with the flat.",
  scanToView: "Scan to view and update food status",
  shareWhatsApp: "Share to WhatsApp",
  downloadPass: "Download Pass",
  printPass: "Print pass",
  shareQrDialog: "Share Pass",
  passMessage: "Food pass for flat ",
  passShareMessage: "ETERNIA FOOD DESK 2026 - Digital Pass",
  passInstruction: "Please carry this QR pass during meal collection for verification. You can request food committee to modify meal choices if you wish.",

  // Form Screen
  cancel: "Cancel",
  editFlat: "Edit Pass",
  addFlatTitle: "Add Pass",
  editSubtitle: "Update the record without changing its QR identity.",
  addSubtitle: "Add details, then generate the flat QR.",
  livePreview: "LIVE PREVIEW",
  paymentModeNotSet: "Payment mode not set",
  noFoodSelected: "Individual items selected per person.",
  blockAndFlat: "Block and Flat",
  blockNo: "Block No.",
  flatNo: "Flat No.",
  flatNoPlaceholder: "Enter Flat No (e.g. 3S)",
  flatNoRequired: "Flat Number is required",
  peopleCount: "People Count",
  foodChoice: "Food Choice",
  foodChoiceInstruction:
    "Select a member (P1, P2...), select a day, then choose the meal.",
  person: "Member",
  personAbbr: "P",
  day: "Day",
  parcelLabel: " Parcel",
  foodTakenPerMeal: "Food taken (per meal)",
  takenLabel: " Taken",
  amount: "Amount",
  paymentMode: "Payment Mode",
  saveChanges: "Save",
  saveGenerateQr: "Save & Generate QR",
  deleteFlatRecord: "Delete",
  deleteConfirmTitle: "Delete pass?",
  deleteConfirmMessage: "This removes flat ",
  deleteConfirmMessageSuffix: " and its food status.",
  deleteButton: "Delete",
  flatExists: "Flat already exists",
  flatExistsMsgPrefix: "Flat ",
  flatExistsMsgSuffix:
    " is already registered. You can edit the existing record now.",
  saveFailed: "Save failed",
  guestTotalError: "Guest Total cannot be less than Guest Taken",
  guestVegTotalError: "Guest Veg Total cannot be less than Guest Veg Taken",
  guestNonVegTotalError: "Guest Non-Veg Total cannot be less than Guest Non-Veg Taken",
  guestTakenError: "Guest Taken cannot exceed total guests",

  // Report Screen
  reportTitle: "Analytics & Reports",
  reportSubtitle: "Detailed data breakdown and summaries.",
  dayWiseReport: "Day Wise Summary",
  mealWiseReport: "Meal Wise Details",
  guestReport: "Guest wise Summary",
  parcelReport: "Parcel wise Summary",
  singleMealReport: "Single Meal Specific",
  notTakenReport: "Meal Not Taken",
  flatWiseReport: "Flat Wise Distribution",
  paymentReport: "Payment Summary",

  // Settings Screen
  settingsTitle: "App Settings",
  settingsSubtitle: "Configure season, days, and dietary rules.",
  seasonNameLabel: "Festive Season Name",
  seasonStatus: "Season Status",
  seasonStatusHelper: "When disabled, all screens will be Read-Only",
  enabledMethods: "ENABLED METHODS",
  paymentIntegration: "Payment Integration",
  paymentIntegrationHelper: "Enable tracking for subscriptions",
  seasonNameHelper: "This festive season name appears on shared QR passes.",
  seasonNamePlaceholder: "e.g. ETERNIA FESTIVAL 2026",
  dayConfigTitle: "Day Configuration",
  activeLabel: "ACTIVE",
  disabledLabel: "DISABLED",
  dayNameLabel: "DAY NAME",
  dayNamePlaceholder: "e.g. Saptami",
  abbrLabel: "ABBREVIATION",
  abbrPlaceholder: "eg. SAP",
  vegOnlyLabel: "Veg only",
  vegOnlyHelper: "Assume all meals are vegetarian for this day",
  parcelSettingsLabel: "PARCEL",
  removeDayLabel: "Remove this day",
  addDayButton: "Add Another Festival Day",
  updateSettingsButton: "Update All Settings",
  settingsUpdated: "Settings updated successfully",
  removeDayConfirmTitle: "Remove Day?",
  removeDayConfirmMessage: "This will hide all data for this day.",
  removeButton: "Remove",
  newDayLabel: "New Day",
  newDayAbbr: "New",
  guestManagementLabel: "Guest Management",
  guestManagementHelper: "Allow tracking extra guest plates on dashboard",
  settings: "Settings",
  support: "SUPPORT",

  // Login Screen
  loginTitle: "Food Desk Login",
  loginSubtitle: "Authorized access only.",
  username: "Username",
  password: "Password",
  loginButton: "Login",
  logoutButton: "Logout",
  invalidCredentials: "Invalid username or password",

  // Footer
  footerCopyright: "© 2026 Eternia Festival Committee",

  // Common
  none: "None",
  back: "Back",
  vegLabel: "Veg",
  nonVegLabel: "Non-Veg",
  breakfastTitle: "Breakfast",
  lunchTitle: "Lunch",
  dinnerTitle: "Dinner",
  vegAbbr: "V",
  nonVegAbbr: "N",
  breakfastAbbr: "B",
  lunchAbbr: "L",
  dinnerAbbr: "D",
  emptyAbbr: "-",
};
