/**
 * Global StyleSheet for the Application
 * Standardized colors, spacing, and component layouts.
 */
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // Root Containers
  root: { flex: 1, backgroundColor: "#f5f1e9" },
  rootOverlay: { flex: 1, backgroundColor: "rgba(245, 241, 233, 0.86)" },
  center: { justifyContent: "center", alignItems: "center" },
  backgroundImage: { opacity: 0.22 },

  // Header & Navigation
  header: {
    backgroundColor: "#253d35",
    paddingTop: 58,
    paddingHorizontal: 24,
    paddingBottom: 28,
  },
  eyebrow: {
    color: "#e5b86a",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.8,
  },
  title: { color: "#fffaf0", fontSize: 34, fontWeight: "800", marginTop: 6 },
  subtitle: { color: "#b9c9bc", fontSize: 15, marginTop: 8 },
  backButton: {
    height: 36,
    alignItems: "flex-start",
    justifyContent: "center",
    marginBottom: 14,
  },
  backIcon: { color: "#f0c977", fontSize: 30, lineHeight: 32, fontWeight: "400" },
  cancelText: {
    color: "#f0c977",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 20,
  },

  // Main Content
  content: { padding: 20, paddingBottom: 96, flexGrow: 1 },
  livePreview: {
    backgroundColor: "#e7d8bd",
    borderRadius: 16,
    padding: 16,
    marginBottom: 8,
  },
  searchBox: {
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#dfd2c0",
    borderRadius: 12,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  searchInput: {
    flex: 1,
    padding: 14,
    paddingLeft: 9,
    color: "#253d35",
    fontSize: 15,
  },
  emptyState: {
    color: "#8d8171",
    fontSize: 14,
    textAlign: "center",
    paddingVertical: 28,
  },
  loadingText: {
    color: "#253d35",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 12,
  },

  // Banner & Feedback
  firebaseBanner: {
    backgroundColor: "#fff0dc",
    borderColor: "#d89153",
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
  },
  firebaseBannerTitle: { color: "#8a4e23", fontSize: 13, fontWeight: "800" },
  firebaseBannerText: {
    color: "#7b5a46",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },

  // Preview Card Parts
  previewTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  previewLabel: {
    color: "#7b5a2d",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  previewTitle: { color: "#253d35", fontSize: 24, fontWeight: "800", marginTop: 3 },
  previewAmount: { color: "#253d35", fontSize: 18, fontWeight: "800" },
  previewMeta: { color: "#58665b", fontSize: 13, fontWeight: "700", marginTop: 10 },
  previewMeals: { color: "#a65b3e", fontSize: 12, fontWeight: "800", marginTop: 8 },
  previewChoice: { color: "#675f55", fontSize: 12, marginTop: 8 },

  // Dashboard & Collection
  collectionCard: {
    backgroundColor: "#e7d8bd",
    borderRadius: 16,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 24,
  },
  collectionAmount: {
    color: "#253d35",
    fontSize: 27,
    fontWeight: "800",
    marginTop: 3,
  },
  collectionBreakdown: {
    color: "#7b5a2d",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 4,
  },
  dashboardCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e7ddce",
  },
  dashboardCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  dashboardDay: { color: "#253d35", fontSize: 19, fontWeight: "800" },
  dashboardPeople: { color: "#a65b3e", fontSize: 13, fontWeight: "800" },
  dashboardMealSection: {
    backgroundColor: "#fdf8ef",
    borderRadius: 14,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#eee5d8",
  },

  // Metric Components
  metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metric: {
    backgroundColor: "#f5f1e9",
    borderRadius: 10,
    padding: 9,
    minWidth: "29%",
    flexGrow: 1,
    alignItems: "center",
  },
  metricValue: { color: "#253d35", fontSize: 18, fontWeight: "800", marginTop: 3 },
  metricLabel: { color: "#675f55", fontSize: 10, fontWeight: "700", marginTop: 2 },

  // Summary Metrics
  summary: {
    backgroundColor: "#e7d8bd",
    borderRadius: 18,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 26,
  },
  summaryLabel: {
    color: "#6d5b46",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  summaryNumber: {
    color: "#253d35",
    fontSize: 38,
    fontWeight: "800",
    marginTop: 2,
  },
  summaryNote: { color: "#7b5a2d", fontSize: 13, fontWeight: "700" },

  // List Items (Flats)
  card: {
    backgroundColor: "#fffaf0",
    padding: 18,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e7ddce",
  },
  cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: 'flex-start', gap: 10 },
  flatLabel: {
    color: "#9a7450",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  flatTitle: {
    color: "#253d35",
    fontSize: 23,
    fontWeight: "800",
    marginTop: 3,
  },
  pill: {
    backgroundColor: "#d9e7d4",
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 8,
    maxWidth: '65%',
  },
  pillText: { color: "#356044", fontSize: 11, fontWeight: "800" },
  people: { color: "#675f55", fontSize: 14, marginTop: 16 },
  cardBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  daysText: { color: "#a65b3e", fontSize: 12, fontWeight: "800" },
  amount: { color: "#253d35", fontSize: 15, fontWeight: "800" },

  // Section Management
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  sectionTitle: {
    color: "#253d35",
    fontSize: 21,
    fontWeight: "800",
    marginBottom: 12,
  },
  footnote: { color: "#8d8171", fontSize: 12, lineHeight: 18, marginTop: 14 },

  // Details & Form Panels
  peoplePanel: {
    backgroundColor: "#fffaf0",
    borderRadius: 14,
    padding: 16,
    marginBottom: 24,
  },
  person: {
    color: "#3d4e44",
    fontSize: 16,
    fontWeight: "700",
    paddingVertical: 5,
  },
  helper: { color: "#8d8171", fontSize: 13, marginBottom: 12 },
  dayRow: {
    backgroundColor: "#fffaf0",
    borderBottomWidth: 1,
    borderBottomColor: "#eee5d8",
    padding: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dayName: { color: "#4d514b", fontSize: 16, fontWeight: "600" },
  personRow: {
    backgroundColor: "#fffaf0",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  personName: {
    color: "#253d35",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 10,
  },
  personDays: { flexDirection: "row", gap: 6 },
  personDay: {
    borderWidth: 1,
    borderColor: "#c9bca9",
    borderRadius: 8,
    paddingVertical: 9,
    paddingHorizontal: 7,
    flex: 1,
    alignItems: "center",
  },
  personDayText: { color: "#58665b", fontSize: 11, fontWeight: "800" },
  slotText: { fontSize: 9, fontWeight: "800", marginTop: 2, letterSpacing: 1 },
  personDayTextOn: { color: "#fff" },

  // Choice & Status Indicators
  vegChoice: { backgroundColor: "#4d8b58", borderColor: "#4d8b58" },
  nonVegChoice: { backgroundColor: "#c35b3b", borderColor: "#c35b3b" },
  takenChoice: { backgroundColor: "#356044", borderColor: "#356044" },
  slotSelected: { backgroundColor: "#356044", borderColor: "#356044" },
  choiceUnselected: { opacity: 0.42 },
  check: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#c9bca9",
    width: 42,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  checkOn: { backgroundColor: "#356044", borderColor: "#356044" },
  checkText: { color: "#fff", fontSize: 11, fontWeight: "800" },

  // Buttons
  primary: {
    backgroundColor: "#c35b3b",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginTop: 24,
  },
  primarySmall: {
    backgroundColor: "#c35b3b",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    flex: 1,
  },
  primaryText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  secondary: {
    borderColor: "#c9bca9",
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    flex: 1,
  },
  secondaryText: { color: "#4c5d51", fontSize: 14, fontWeight: "800" },
  addButton: {
    backgroundColor: "#c35b3b",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
  },
  addButtonText: { color: "#fff", fontWeight: "800" },
  deleteButton: {
    borderColor: "#b34e45",
    borderWidth: 1,
    borderRadius: 12,
    padding: 15,
    alignItems: "center",
    marginTop: 12,
    marginBottom: 20,
  },
  deleteText: { color: "#b34e45", fontSize: 15, fontWeight: "800" },

  // Actions
  actions: { flexDirection: "row", gap: 10, marginTop: 12, flexWrap: "wrap" },
  compactActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginLeft: "auto",
    flexWrap: "wrap",
  },
  compactSecondary: {
    borderColor: "#c9bca9",
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  actionLabel: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  actionLabelText: { fontSize: 14, fontWeight: "800" },

  // Form Controls
  label: {
    color: "#4e5c51",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 16,
    marginBottom: 8,
  },
  row: { flexDirection: "row", gap: 10, alignItems: "flex-start" },
  fieldHalf: { flex: 1 },
  input: {
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#dfd2c0",
    borderRadius: 10,
    padding: 13,
    fontSize: 15,
    color: "#253d35",
  },
  inputHalf: {
    flex: 1,
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#dfd2c0",
    borderRadius: 10,
    padding: 13,
    fontSize: 15,
    color: "#253d35",
  },

  // Dropdown Component
  dropdownWrap: { flex: 1, minWidth: 0, position: "relative", zIndex: 20 },
  dropdownButton: {
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#dfd2c0",
    borderRadius: 10,
    padding: 13,
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownValue: { color: "#253d35", fontSize: 15, flexShrink: 1 },
  dropdownChevron: { color: "#356044", fontSize: 11, marginLeft: 6 },
  dropdownMenu: {
    position: "absolute",
    top: 76,
    left: 0,
    right: 0,
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#dfd2c0",
    borderRadius: 10,
    maxHeight: 180,
    overflow: "hidden",
    zIndex: 30,
    elevation: 8,
  },
  dropdownMenuNoLabel: { top: 52 },
  dropdownModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(20, 30, 25, 0.55)",
    justifyContent: "center",
    padding: 24,
  },
  dropdownModalCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 16,
    padding: 16,
    maxHeight: "72%",
  },
  dropdownModalTitle: {
    color: "#253d35",
    fontSize: 19,
    fontWeight: "800",
    marginBottom: 10,
  },
  dropdownModalList: { maxHeight: 360 },
  dropdownModalCancel: {
    borderWidth: 1,
    borderColor: "#c9bca9",
    borderRadius: 10,
    padding: 13,
    alignItems: "center",
    marginTop: 12,
  },
  dropdownOption: {
    paddingVertical: 10,
    paddingHorizontal: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#eee5d8",
  },
  dropdownOptionSelected: { backgroundColor: "#d9e7d4" },
  dropdownOptionText: { color: "#58665b", fontSize: 14, fontWeight: "700" },
  dropdownOptionTextSelected: { color: "#356044" },

  // Custom Selectors
  choiceRow: { flexDirection: "row", gap: 10 },
  choice: {
    borderWidth: 1,
    borderColor: "#c9bca9",
    borderRadius: 10,
    padding: 12,
    flex: 1,
    alignItems: "center",
  },
  choiceOn: { backgroundColor: "#356044", borderColor: "#356044" },
  noneChoice: { backgroundColor: "transparent", borderColor: "#c9bca9" },
  choiceText: { color: "#58665b", fontWeight: "700" },
  choiceTextOn: { color: "#fff" },
  selectorLabel: {
    color: "#4e5c51",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 10,
    marginBottom: 6,
  },
  selectorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 4,
  },
  selector: {
    borderWidth: 1,
    borderColor: "#c9bca9",
    borderRadius: 9,
    paddingVertical: 9,
    paddingHorizontal: 11,
  },
  selectorOn: { backgroundColor: "#356044", borderColor: "#356044" },
  selectorText: { color: "#58665b", fontSize: 12, fontWeight: "700" },
  selectorTextOn: { color: "#fff" },
  currentChoice: {
    color: "#253d35",
    fontSize: 14,
    fontWeight: "800",
    marginTop: 12,
    marginBottom: 8,
  },

  // Menu Management
  menuField: { marginBottom: 12 },
  menuDayCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e7ddce",
    overflow: "hidden",
  },
  menuDayHeader: {
    backgroundColor: "#e7d8bd",
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  menuDayTitle: { color: "#253d35", fontSize: 18, fontWeight: "800" },
  menuDayBody: { padding: 16, gap: 16 },
  mealDisplayRow: {
    borderBottomWidth: 1,
    borderBottomColor: "#eee5d8",
    paddingBottom: 12,
  },
  mealDisplayHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 },
  mealDisplayTitle: { color: "#356044", fontSize: 15, fontWeight: "800" },
  mealItemsContainer: { gap: 6, paddingLeft: 26 },
  mealTypeSection: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  mealItemsText: {
    color: "#58665b",
    fontSize: 14,
    lineHeight: 20,
    flex: 1,
    fontWeight: "600",
  },
  mealEditor: { marginBottom: 20 },
  mealEditorTitle: {
    color: "#4e5c51",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 8,
  },
  mealEditorInputs: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  mealInput: {
    flex: 1,
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#dfd2c0",
    borderRadius: 10,
    padding: 10,
    fontSize: 14,
    color: "#253d35",
  },
  typeToggle: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 70,
    alignItems: "center",
  },
  typeToggleText: { color: "#fff", fontSize: 11, fontWeight: "800" },
  addSmall: {
    backgroundColor: "#c35b3b",
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  itemList: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  itemBadge: {
    backgroundColor: "#f5f1e9",
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#dfd2c0",
  },
  itemBadgeText: { color: "#675f55", fontSize: 12, fontWeight: "700" },
  dot: { width: 8, height: 8, borderRadius: 4 },
  mealSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  menuSummaryLabel: { color: "#253d35", fontSize: 13, fontWeight: "800", minWidth: 18 },
  inlineItemList: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexWrap: "wrap",
    flex: 1,
  },
  menuBox: {
    backgroundColor: "#fdf8ef",
    borderRadius: 10,
    padding: 10,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#eee5d8",
  },
  menuText: { color: "#675f55", fontSize: 13, fontWeight: "600", marginBottom: 3 },
  dayMenuSection: {
    borderBottomWidth: 1,
    borderBottomColor: "#eee5d8",
    paddingBottom: 10,
    marginBottom: 10,
  },
  menuSummaryInline: { marginTop: 4, paddingLeft: 4 },
  menuSummaryText: {
    color: "#675f55",
    fontSize: 13,
    fontStyle: "italic",
    marginBottom: 2,
  },

  // Selection Matrix
  daysGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  dayChoice: {
    borderWidth: 1,
    borderColor: "#c9bca9",
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 13,
  },
  mealRow: {
    backgroundColor: "#fffaf0",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    gap: 8,
  },
  mealCounter: { flexDirection: "row", alignItems: "center", gap: 8 },
  mealLabel: { color: "#58665b", fontWeight: "700", width: 68, fontSize: 12 },
  counterButton: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#d9e7d4",
    alignItems: "center",
    justifyContent: "center",
  },
  counterText: { color: "#356044", fontWeight: "800", fontSize: 18 },
  counterValue: {
    color: "#253d35",
    fontWeight: "800",
    minWidth: 18,
    textAlign: "center",
  },

  // QR & Scanning
  qrContent: { alignItems: "center", padding: 24 },
  qrBox: {
    backgroundColor: "#fff",
    padding: 18,
    borderRadius: 18,
    marginTop: 20,
  },
  qrCaption: {
    color: "#253d35",
    fontWeight: "800",
    fontSize: 16,
    marginTop: 22,
  },
  qrLink: { color: "#8d8171", fontSize: 11, marginTop: 8 },
  scanner: { flex: 1, backgroundColor: "#000" },
  camera: { flex: 1 },
  scannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
  },
  scannerTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 58,
    paddingHorizontal: 24,
    zIndex: 100,
  },
  scannerCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  scannerBottom: {
    position: "absolute",
    bottom: 60,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  scanFrame: {
    width: 260,
    height: 260,
    borderWidth: 2,
    borderColor: "#f0c977",
    borderRadius: 30,
    backgroundColor: "transparent",
  },
  scanHint: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  scanError: {
    color: "#ffb09c",
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 20,
  },

  // Global Footer
  footer: { paddingVertical: 24, paddingBottom: 40, alignItems: "center", opacity: 0.8 },
  footerText: { color: "#8d8171", fontSize: 12, fontWeight: "600" },
});
