/**
 * Centralized Type Definitions
 * Re-exports domain types and defines application-specific types.
 */
import {
  SubscriptionRecord,
  FoodMenu,
  DayMenu,
  MealMenu,
  MealChoice,
  MealSlot,
  TakenState,
  MealType,
  DietaryOption,
  normalizeChoice,
  normalizeSlot,
  toBool,
  DietType,
  AppScreen,
  ReportType,
  PaymentMode,
  UserRole,
  PaymentEntry,
  ActivityLog,
  ActivityAction,
  ActivityModule,
  AppThemeMode,
  ConfigDay,
  AppConfig,
  PaymentConfig,
  Note,
  MealMetrics,
  KitchenMetrics,
  CheckoutSource,
  FreeMealCheckoutSource,
  getPassDisplayLabel,
  AppVersionInfo,
  DietaryVariety,
  VarietyMenu,
  ChatMessage,
  UserPresence,
  ChatUser,
  MessageStatus,
  PackageApplicability,
  FoodPackage,
  AppliedPackageInfo,
} from "./domain";

export enum FilterMode {
  ALL = "all",
  SUBSCRIBED = "subscribed",
  KIDS = "kids",
  PARCEL = "parcel",
  VEG_ONLY = "vegOnly",
  MISSED = "missed",
  SPECIAL_ONLY = "specialOnly",
  PACKAGE = "package",
}

export type Day = string;
export type Screen = AppScreen;

export type Subscription = SubscriptionRecord;

export {
  SubscriptionRecord,
  FoodMenu,
  DayMenu,
  MealMenu,
  MealChoice,
  MealSlot,
  TakenState,
  MealType,
  DietaryOption,
  normalizeChoice,
  normalizeSlot,
  toBool,
  DietType,
  AppScreen,
  ReportType,
  UserRole,
  PaymentMode,
  PaymentEntry,
  ActivityLog,
  ActivityAction,
  ActivityModule,
  AppThemeMode,
  ConfigDay,
  DietaryVariety,
  VarietyMenu,
  getPassDisplayLabel,
  AppVersionInfo,
  AppConfig,
  PaymentConfig,
  Note,
  CheckoutSource,
  FreeMealCheckoutSource,
  MealMetrics,
  KitchenMetrics,
  ChatMessage,
  UserPresence,
  ChatUser,
  MessageStatus,
  PackageApplicability,
  FoodPackage,
  AppliedPackageInfo,
};
